---
- name: 'Архитектура сети'
  hosts: all
  become: yes
  tasks:
    - name: 'Отключение ufw на inetRouter'
      systemd:
        name: ufw
        state: stopped
        enabled: false
      when: (ansible_hostname == "inetRouter")

    - name: 'Настройка NAT на inetRouter'
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "./template/iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "./template/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")
    
    - name: 'Включаем форвардинг'
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"
    - name: disable default route
      template: 
        src: ./template/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644
      when: (ansible_hostname != "inetRouter") 
    - name: add default gateway for centralRouter
      template: 
        src: "./template/50-vagrant_{{ ansible_hostname }}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: 'restart all hosts'
      reboot:
        reboot_timeout: 600

    - name: 'Установка traceroute'
      shell: apt install -y traceroute
